version: "3.9"
services:
  nginx:
    build: ./nginx/
    ports:
      - 4400:80
    volumes:
      - ./movie/:/var/www/html/

  php:
    build: ./movie/
    expose:
      - 9000
    volumes:
      - ./movie/:/var/www/html/

  DB:
    platform: linux/amd64 # for platform error on Apple M1 chips
    restart: always
    env_file: .env
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: DB
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - DB
